# Generated by Django 3.1.5 on 2021-01-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papermanager', '0003_auto_20210121_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstorage',
            name='group_max_storage',
        ),
    ]
